name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          file: mayhem/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image: ${{ steps.meta.outputs.tags }}

  mayhem:
    needs: build
    name: 'fuzz ${{ matrix.target }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - fuzz_plist_ser_deser_generic
          - fuzz_qset_entity
          - fuzz_handle_rtps_message
          - fuzz_locator_from_string
          - fuzz_config_init
        # - fuzz_nn_participant_generic_message_init

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Start analysis for ${{ matrix.mayhemfile }}
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ needs.build.outputs.image }} --file mayhem/${{ matrix.target }}.mayhemfile --duration 300
          sarif-output: sarifs/${{ matrix.target }}.sarif
  sarif:
    needs: mayhem
    name: SARIF
    runs-on: ubuntu-latest
    steps:
      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarifs
